apiVersion: v1
kind: Service
metadata:
  name: {{ include "dfastllm.fullname" . }}
  labels:
    {{- include "dfastllm.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.server.port }}
      protocol: TCP
      name: http
  selector:
    {{- include "dfastllm.selectorLabels" . | nindent 4 }}

